// products.ts

import { Product } from "../interface/interfaces";

export const products: Product[] = [
  {
    id: 1,
    name: 'Smartphone',
    description: 'Powerful and sleek smartphone for your daily needs.',
    longDescription: 'Experience cutting-edge technology with our powerful and sleek smartphone. Packed with advanced features, it\'s designed to meet all your daily communication and entertainment needs. With a stunning display and high-performance capabilities, this smartphone is a perfect companion for a modern lifestyle.',
    price: 599.99,
    image: 'https://images.unsplash.com/photo-1634403665481-74948d815f03?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Electronics',
    isFavourite: false,
    isBestseller: true,
    stock: 10,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 2,
    name: 'Laptop',
    description: 'High-performance laptop with a stunning display.',
    longDescription: 'Boost your productivity with our high-performance laptop featuring a stunning display and powerful capabilities. Whether you\'re working on complex tasks or enjoying multimedia content, this laptop delivers an exceptional experience. Stay ahead with the latest technology and sleek design.',
    price: 1299.99,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Electronics',
    isFavourite: false,
    isBestseller: false,
    stock: 15,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 3,
    name: 'Headphones',
    description: 'Noise-canceling headphones for an immersive audio experience.',
    longDescription: 'Immerse yourself in crystal-clear sound with our noise-canceling headphones. Designed for an immersive audio experience, these headphones deliver high-quality sound and comfort. Whether you\'re commuting or relaxing at home, these headphones provide the perfect escape into your favorite music or podcasts.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Electronics',
    isFavourite: false,
    isBestseller: false,
    stock: 20,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 4,
    name: 'Fitness Tracker',
    description: 'Track your fitness and stay active with this smart fitness tracker.',
    longDescription: 'Stay on top of your fitness goals with our smart fitness tracker. This advanced device monitors your activity, heart rate, and more, helping you maintain a healthy and active lifestyle. With its sleek design and user-friendly features, its the perfect companion for your fitness journey.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1576243345690-4e4b79b63288?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Electronics',
    isFavourite: false,
    isBestseller: true,
    stock: 15,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 5,
    name: 'Coffee Maker',
    description: 'Enjoy freshly brewed coffee at home with this advanced coffee maker.',
    longDescription: 'Indulge in the rich aroma of freshly brewed coffee with our advanced coffee maker. Designed for coffee enthusiasts, this appliance brings the cafe experience to your home. With customizable settings and a sleek design, its the perfect addition to your kitchen for a delightful coffee ritual.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1593369196682-6d8ec9ff3ae0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Appliances',
    isFavourite: false,
    isBestseller: true,
    stock: 12,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 6,
    name: 'Smartwatch',
    description: 'Stay connected and track your health with this stylish smartwatch.',
    longDescription: 'Elevate your lifestyle with our stylish smartwatch. Stay connected, track your health, and receive notifications on the go. With its sleek design and advanced features, this smartwatch is a perfect blend of fashion and functionality. Make a statement while staying in control of your day.',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1617625802912-cde586faf331?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Electronics',
    isFavourite: false,
    isBestseller: true,
    stock: 18,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 7,
    name: 'Wireless Earbuds',
    description: 'Compact and wireless earbuds for an on-the-go audio experience.',
    longDescription: 'Experience freedom with our compact and wireless earbuds. Designed for on-the-go audio enthusiasts, these earbuds deliver high-quality sound without the hassle of wires. With a comfortable fit and long battery life, they are perfect for your active lifestyle.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1590658006821-04f4008d5717?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Electronics',
    isFavourite: false,
    isBestseller: false,
    stock: 25,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 8,
    name: 'Tablet',
    description: 'Versatile tablet for work and entertainment on the move.',
    longDescription: 'Enhance your productivity and entertainment on the move with our versatile tablet. Featuring a high-resolution display and powerful performance, this tablet is perfect for work, entertainment, and creative tasks. Stay connected and enjoy a seamless digital experience.',
    price: 299.99,
    image: 'https://images.unsplash.com/photo-1527698266440-12104e498b76?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Electronics',
    isFavourite: false,
    isBestseller: false,
    stock: 8,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 9,
    name: 'Robot Vacuum Cleaner',
    description: 'Effortlessly keep your home clean with this smart robot vacuum cleaner.',
    longDescription: 'Enjoy a clean and tidy home effortlessly with our smart robot vacuum cleaner. Equipped with advanced sensors and powerful suction, it navigates through your space, keeping every corner free from dust and debris. Embrace convenience and automation in your daily cleaning routine.',
    price: 249.99,
    image: 'https://images.unsplash.com/photo-1603618090561-412154b4bd1b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Appliances',
    isFavourite: false,
    isBestseller: false,
    stock: 10,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 10,
    name: 'Gaming Console',
    description: 'Immerse yourself in the world of gaming with this powerful gaming console.',
    longDescription: 'Experience unparalleled gaming adventures with our powerful gaming console. Whether you\'re a casual gamer or a hardcore enthusiast, this console delivers stunning graphics and immersive gameplay. Elevate your gaming experience with cutting-edge technology and top-tier performance.',
    price: 499.99,
    image: 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?q=80&w=2127&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Electronics',
    isFavourite: false,
    isBestseller: false,
    stock: 5,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 11,
    name: 'T-Shirt',
    description: 'Comfortable cotton T-shirt for everyday wear.',
    longDescription: 'Experience ultimate comfort with our cotton T-shirt, perfect for everyday wear. Crafted with high-quality materials, it provides a soft and breathable feel. The timeless design makes it a versatile addition to your wardrobe, suitable for various occasions.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Clothes',
    isFavourite: false,
    isBestseller: true,
    stock: 30,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 12,
    name: 'Jeans',
    description: 'Classic denim jeans for a timeless look.',
    longDescription: 'Achieve a timeless and stylish look with our classic denim jeans. Crafted for durability and comfort, these jeans are a wardrobe essential. The versatile design makes them suitable for casual or dressed-up occasions, offering a perfect blend of fashion and functionality.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Clothes',
    isFavourite: false,
    isBestseller: false,
    stock: 20,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 13,
    name: 'Sneakers',
    description: 'Stylish sneakers for a casual and trendy appearance.',
    longDescription: 'Step into style with our trendy sneakers, designed for a casual and fashionable look. Whether youre running errands or meeting friends, these sneakers provide comfort and flair. The sleek design and quality craftsmanship make them a must-have in your shoe collection.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1608667508764-33cf0726b13a?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Clothes',
    isFavourite: false,
    isBestseller: true,
    stock: 25,
    orderedQuantity: 1,
    opinions: []
  },
  {
    id: 14,
    name: 'Pokeball',
    description: 'The Pokeball is an exciting toy inspired by the popular world of Pokemon.',
    longDescription: 'Embark on a journey into the enchanting world of Pokemon with our Pokeball toy. This exciting and iconic toy brings the magic of Pokemon to life, allowing young trainers to catch and imagine their favorite creatures. The Pokeball is a must-have for every Pokemon enthusiast, providing hours of imaginative play.',
    price: 20.99,
    image: 'https://images.pexels.com/photos/7772559/pexels-photo-7772559.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Toys',
    isFavourite: false,
    isBestseller: true,
    stock: 35,
    orderedQuantity: 1,
    opinions: []
  },
  
];
