// products.ts

import { Product } from "../interface/interfaces";

export const products: Product[] = [
  {
    id: 1,
    name: 'Smartphone',
    description: 'Powerful and sleek smartphone for your daily needs.',
    price: 599.99,
    image: 'smartphone.jpg',
    category: 'Electronics',
  },
  {
    id: 2,
    name: 'Laptop',
    description: 'High-performance laptop with a stunning display.',
    price: 1299.99,
    image: 'laptop.jpg',
    category: 'Electronics',
  },
  {
    id: 3,
    name: 'Headphones',
    description: 'Noise-canceling headphones for an immersive audio experience.',
    price: 149.99,
    image: 'headphones.jpg',
    category: 'Electronics',
  },
  {
    id: 4,
    name: 'Fitness Tracker',
    description: 'Track your fitness and stay active with this smart fitness tracker.',
    price: 79.99,
    image: 'fitness-tracker.jpg',
    category: 'Electronics',
  },
  {
    id: 5,
    name: 'Coffee Maker',
    description: 'Enjoy freshly brewed coffee at home with this advanced coffee maker.',
    price: 89.99,
    image: 'coffee-maker.jpg',
    category: 'Appliances',
  },
  {
    id: 6,
    name: 'Smartwatch',
    description: 'Stay connected and track your health with this stylish smartwatch.',
    price: 199.99,
    image: 'smartwatch.jpg',
    category: 'Electronics',
  },
  {
    id: 7,
    name: 'Wireless Earbuds',
    description: 'Compact and wireless earbuds for an on-the-go audio experience.',
    price: 69.99,
    image: 'wireless-earbuds.jpg',
    category: 'Electronics',
  },
  {
    id: 8,
    name: 'Tablet',
    description: 'Versatile tablet for work and entertainment on the move.',
    price: 299.99,
    image: 'tablet.jpg',
    category: 'Electronics',
  },
  {
    id: 9,
    name: 'Robot Vacuum Cleaner',
    description: 'Effortlessly keep your home clean with this smart robot vacuum cleaner.',
    price: 249.99,
    image: 'robot-vacuum.jpg',
    category: 'Appliances',
  },
  {
    id: 10,
    name: 'Gaming Console',
    description: 'Immerse yourself in the world of gaming with this powerful gaming console.',
    price: 499.99,
    image: 'gaming-console.jpg',
    category: 'Electronics',
  },
  {
    id: 11,
    name: 'T-Shirt',
    description: 'Comfortable cotton T-shirt for everyday wear.',
    price: 19.99,
    image: 't-shirt.jpg',
    category: 'Clothing',
  },
  {
    id: 12,
    name: 'Jeans',
    description: 'Classic denim jeans for a timeless look.',
    price: 39.99,
    image: 'jeans.jpg',
    category: 'Clothing',
  },
  {
    id: 13,
    name: 'Sneakers',
    description: 'Stylish sneakers for a casual and trendy appearance.',
    price: 59.99,
    image: 'sneakers.jpg',
    category: 'Clothing',
  },
];
